//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculodePedidos.SharedKernel {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalculodePedidos_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalculodePedidos_Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculodePedidos.SharedKernel.CalculodePedidos.Resources", typeof(CalculodePedidos_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe base del pedido no puede ser igual o inferior a cero..
        /// </summary>
        public static string BaseNoPuedeSerCero {
            get {
                return ResourceManager.GetString("BaseNoPuedeSerCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio informar el código de pais..
        /// </summary>
        public static string CodigoPaisNoInformado {
            get {
                return ResourceManager.GetString("CodigoPaisNoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El descuento aplicado es :.
        /// </summary>
        public static string ElDescuentoAplicadoEs {
            get {
                return ResourceManager.GetString("ElDescuentoAplicadoEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El impuesto aplicado es :.
        /// </summary>
        public static string ElImpuestoAplicadoEs {
            get {
                return ResourceManager.GetString("ElImpuestoAplicadoEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado. Pulse cualquier tecla para salir..
        /// </summary>
        public static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el código de pais de la operación (se aplicacará el impuesto correspondiente) :.
        /// </summary>
        public static string IntroduzcaPais {
            get {
                return ResourceManager.GetString("IntroduzcaPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el porcentage de descuento a aplicar en base 100 :.
        /// </summary>
        public static string IntroduzcaPorcentajeDto {
            get {
                return ResourceManager.GetString("IntroduzcaPorcentajeDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el precio por unidad :.
        /// </summary>
        public static string IntroduzcaPrecioUnidad {
            get {
                return ResourceManager.GetString("IntroduzcaPrecioUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la cantidad de unidades :.
        /// </summary>
        public static string IntroduzcaUnidades {
            get {
                return ResourceManager.GetString("IntroduzcaUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de paises disponibles para la operación :.
        /// </summary>
        public static string ListadoPaises {
            get {
                return ResourceManager.GetString("ListadoPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio total :.
        /// </summary>
        public static string PrecioTotal {
            get {
                return ResourceManager.GetString("PrecioTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio informar el precio por unidad..
        /// </summary>
        public static string PrecioUnidadNoInformado {
            get {
                return ResourceManager.GetString("PrecioUnidadNoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio por unidad no puede ser cero..
        /// </summary>
        public static string PrecioUnidadNoPuedeSerCero {
            get {
                return ResourceManager.GetString("PrecioUnidadNoPuedeSerCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio informar el número de unidades del pedido..
        /// </summary>
        public static string UnidadesNoInformadas {
            get {
                return ResourceManager.GetString("UnidadesNoInformadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de unidades no puede ser cero..
        /// </summary>
        public static string UnidadesNoPuedenSerCero {
            get {
                return ResourceManager.GetString("UnidadesNoPuedenSerCero", resourceCulture);
            }
        }
    }
}
